title: Mohan Zhang's Homepage
page-top-title: Mohan Zhang
top-section-bg-text: Artificial Intelligence
home-subtitle: Mohan Zhang&ensp;|&ensp;张墨涵
copyright-text: '&copy; Mohan Zhang 2023-2027. All Rights Reserved.'
